# Generated by Django 2.1.2 on 2018-12-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date_usage',
            field=models.DateTimeField(null=True, verbose_name='Usage date'),
        ),
        migrations.AlterField(
            model_name='token',
            name='string',
            field=models.CharField(default='a7e7f0bc6a3d9bc43c6240af42ac07909f303c39', max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='used_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
