# Generated by Django 2.1.4 on 2018-12-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plex', '0005_auto_20181223_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='string',
            field=models.CharField(default='e5fb47ff6ccb4e96ffc4d11c8a74eb82701f04e6', max_length=255),
        ),
    ]
