# Generated by Django 2.1.4 on 2018-12-26 13:40

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plex', '0006_auto_20181223_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='libraries',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='token',
            name='string',
            field=models.CharField(default='bfe70876976541214b1f7296153dfdf7d163a8ef', max_length=255),
        ),
    ]
