# Generated by Django 2.1.4 on 2018-12-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plex', '0008_auto_20181226_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='Invitation',
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['date_creation'], 'verbose_name': 'invitation'},
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='string',
            new_name='token',
        ),
    ]
