# Generated by Django 2.1.4 on 2018-12-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plex', '0009_auto_20181229_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
