# Generated by Django 2.2.2 on 2019-06-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plex', '0010_invitation_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='sent',
        ),
        migrations.AddField(
            model_name='invitation',
            name='sent_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
