# Generated by Django 2.2.2 on 2019-06-29 14:12

from django.db import migrations, models
import jsonfield.fields
import plex.models


class Migration(migrations.Migration):

    dependencies = [
        ('plex', '0011_auto_20190628_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['date_creation'], 'verbose_name': 'Invitation'},
        ),
        migrations.AlterField(
            model_name='invitation',
            name='libraries',
            field=jsonfield.fields.JSONField(default=dict, verbose_name='Libraries'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sent_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sent to'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default=plex.models.genString, max_length=255, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='used_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Used by'),
        ),
    ]
