# Generated by Django 2.1.2 on 2018-12-22 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(default='a152cca9fef37a6adcfa6bd0a3d0e49430e3b1ce', max_length=255)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('date_usage', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Usage date')),
                ('used_by', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'token',
                'ordering': ['date_creation'],
            },
        ),
    ]
