# Generated by Django 2.1.2 on 2018-12-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_auto_20181223_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='string',
            field=models.CharField(default='df0bb6846d17820996b9b49d89c59d7100e88f9f', max_length=255),
        ),
    ]
