# Generated by Django 2.1.2 on 2018-12-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_auto_20181223_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date_usage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Usage date'),
        ),
        migrations.AlterField(
            model_name='token',
            name='string',
            field=models.CharField(default='040529d699805055a5b12c0de2907133c1e6a005', max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='used_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
