# Generated by Django 2.1.4 on 2018-12-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0004_auto_20181223_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='string',
            field=models.CharField(default='6d7d0dece18aaa2882f504f011454641b0a9dc90', max_length=255),
        ),
    ]
