# Generated by Django 2.1.4 on 2018-12-26 15:11

from django.db import migrations, models
import invite.models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0007_auto_20181226_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='string',
            field=models.CharField(default=invite.models.genString, max_length=255),
        ),
    ]
